### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/truthy-falsy-quiz#1]
Hey @chrisvfritz - can you give me a code review on this?

https://katiemfritz.github.io/truthy-falsy-quiz/

- Is there code that could/should be simplified? Am I using roundabout approaches?
- Are my variable names and comments clear to you (can you tell what's going on easily)?
- Am I doing anything that's just weird?
- Can you break it?

**Comment by chrisvfritz** [comment]
- It's generally a good idea to minimize the number of global variables you have. Instead, prefer declaring them local to a function, then passing information to other functions. This makes your program _much_ easier to think about, because you can trace exactly where values are coming from, rather than trying to guess where they might have been modified. Try this with `randomQuestion`, `answer`, and `explanation`.
- Try to combine the `correct` and `incorrect` messages into an object that makes them more apparent what they are. The object could be called `messages` or `responses`, for example. Otherwise, when I just see `correct`, it's not clear to me what kind of value it might have.
- The function name `refresh` could be a little confusing, since _refreshing_ means something very specific in the browser - and we're not doing that.

**Comment by KatieMFritz** [comment]
Thank you for the suggestions!

>  Instead, prefer declaring them local to a function, then passing information to other functions.

I don't understand how to do this. For example, if I first declare `randomQuestion` in my `getQuestion` function, then the `refresh` function thinks it's undefined. What am I missing?

**Comment by chrisvfritz** [comment]
I _think_ we addressed this when we talked yesterday, but let me know if I'm mistaken. 🙂

**Comment by KatieMFritz** [comment]
Nope, you answered my questions and then some. Thanks! 🎉 🌮 

How's it looking now? https://katiemfritz.github.io/truthy-falsy-quiz/

**Comment by chrisvfritz** [comment]
Is the `git` next to the button intentional? 😛

**Comment by KatieMFritz** [comment]
Oops. Thanks!
